# Heap for the Gradle daemon.
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.configuration-cache=false
# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
# Mod Properties
mod_version=2.2.0
maven_group=com.github.xandergos
archives_base_name=terrain-diffusion-mc
# Dependencies
fabric_version=0.155.2+26.1.2
